### ISSUE TITLE
Modificare template su Google Docs

### ISSUE THREAD

**Issue by alterat** [italia/docs-italia-template-conversione#6]
Il link a Google Docs nel Readme è sbagliato.

**Comment by pablopers** [comment]
farne un altro rST?

**Comment by alterat** [comment]
Ciao @pablopers! Intendi creare un RST che corrisponda al Google Doc?

**Comment by pablopers** [comment]
Ciao @atorin, in effetti mi sono espresso male e me ne scuso. Sono passato decisamente oltre la tua segnalazione del Doc non giusto per rilanciare e proporne una versione compilata con il nuovo tema. In pratica:  
1. guardando il README mi chiedevo se non fosse il caso di inserire, magari affiancandola al google docs (giusto), anche la versione convertita e compilata con il nuovo tema. Il Repo confronta i file e pensavo che forse un link al "risultato finale" non guastava anche alla luce del fatto che un file esempio.rst effettivamente non esiste più, ma è sostituito dalla directory template-rst. 
2. inoltre manca il riferimento al file .odt in riferimento a Libre Office e i file non sono più "esempio" ma template.
